### ISSUE TITLE
Prev and Next button not working correct on asNavFor 

### ISSUE THREAD

**Issue by quebec87** [metafizzy/flickity#204] opened 2015-08-04 16:14 UTC
If there are many images in the nav gallery, (for example, 20 images), I will have to click on Next button at least 4-5 times to make the thumbnails moving. (the wider the screen is, the more click needed)

When it goes to the end, will have to click on Prev button many times to get it moving back.

If I turn off "contain":true, Prev and Next button works fine.

Here is a produced case http://codepen.io/quebec87/pen/XbOKgP  thanks

**Comment by desandro** [comment] 2015-08-20 20:12
I'll chalk this up to a feature request for sliding by group. Closing as a duplicate of #22

**Closed by desandro** 2015-08-20 20:12 UTC
