### ISSUE TITLE
Double move on prev/next button tap on Android & Chrome in Touch view

### ISSUE THREAD

**Issue by TheHoover** [metafizzy/flickity#849] opened 2018-10-09 09:38 UTC
Version 2.1.2
Android 5.1.1
Chrome v69 - dev tools mobile touch mode

The right/left arrows shift the carousel on twice.
Same as issue #122 https://github.com/metafizzy/flickity/issues/122

**Test case:** https://codepen.io/renato2016/pen/dqqddZ?page=1&

**Comment by TheHoover** [comment] 2018-10-10 09:31
Would appear to be when carousel hosted in an iframe, mouseDown gets fired which makes the button the activeElement. No mouseDown when non in an iframe.

**Comment by desandro** [comment] 2018-12-24 17:11
I'm not able to reproduce and no one has chimed in. Closing!

**Closed by desandro** 2018-12-24 17:11 UTC
