### ISSUE TITLE
Cells 'fall off' if wrapAround true, but not enough cells to occupy page

### ISSUE THREAD

**Issue by howells** [metafizzy/flickity#272] opened 2015-10-15 13:56 UTC
Not a major issue but I find that if there aren't enough cells to fill a full-width carousel at certain screensizes, the cells have a glitchy behaviour where they are added and fall off. It's clear why this happens but to get around I double up the carousel to make sure it's smooth regardless of the number of cells. Wondered if this could be handled by Flickity somehow?

http://quick.as/zxl3syj3a

**Comment by desandro** [comment] 2015-10-15 14:22
Thanks for reporting this issue. This is a duplicate of #95. I still feel there's no good solution.

> Yes, this could be helpful. But I feel this is an edge case. Either your content works with wrapAround, or it doesn't. Catering to both use cases could be cumbersome.

If there's not enough content to fill the container, consider not initializing Flickity on that page.

**Comment by howells** [comment] 2015-10-15 14:23
Yeah fair enough

**Closed by desandro** 2015-10-15 14:22 UTC
