### ISSUE TITLE
Using arrow keys on asNavFor carousel doesn't update the main carousel

### ISSUE THREAD

**Issue by danielsamuels** [metafizzy/flickity#421] opened 2016-07-22 09:32 UTC
**Test case:** https://codepen.io/desandro/pen/wByaqj

Reproduction steps:

1. Click on the main navigation and use the arrow keys to move left and right, carousel navigates as expected.
2. Click on the asNavFor carousel and use the arrow keys to move left and right, the control navigation updates, but the changes aren't reflected in the primary carousel.

(Note: There seems to be a related bug where the asNavFor carousel will move left/right (if the browser is narrow enough) but not update the active cell.)

**Comment by desandro** [comment] 2016-07-22 12:50
Thanks for taking a look here. The navigation gallery is working as intended. It's a conscious UI behavior that selecting a cell from navigation gallery does not select it from the content gallery. This allows the user to pan around the navigation gallery without it automatically changing the selected gallery. In my testing, this felt more natural than having the galleries completely synced up.

I did make a Flickity extension that does syncing, [flickity-sync](https://github.com/metafizzy/flickity-sync), if that is what you're looking for. Try the demo http://codepen.io/desandro/pen/OPZJmE

Duplicate of https://github.com/metafizzy/flickity/issues/58#issuecomment-75374590

**Comment by danielsamuels** [comment] 2016-07-22 12:51
Great, I'll make use of the sync plugin. Thanks!

**Closed** 2016-07-22 13:59 UTC
Labels: duplicate

**Comment by aeu** [comment] 2019-04-02 12:11
This was a handy thread to find, thank you.
