### ISSUE TITLE
Lazy Load and Wrap Around issue

### ISSUE THREAD

**Issue by spectralshadow514** [metafizzy/flickity#618] opened 2017-08-17 13:33 UTC
With Lazy Load and Wrap Around active, there's an odd visual glitch when scrolling backwards through the gallery the first time around:
https://codepen.io/anon/pen/VzyxWM
It works fine when everything is loaded, but prior to that the animation is.. choppy.

**Comment by desandro** [comment] 2017-08-18 19:03
Duplicate of #231

**Comment by desandro** [comment] 2017-08-18 19:03
Thanks for reporting this issue. We already have an issue opened for this bug.

**Closed by desandro** 2017-08-18 19:03 UTC
