### ISSUE TITLE
1 of 3 element disappear when the slider has 3 exact slides

### ISSUE THREAD

**Issue by ballanz89** [metafizzy/flickity#660] opened 2017-11-22 08:54 UTC
Is this an issue or a know limitation? 
Should I have always more < li > elements than the ones who I show initially?
Video explanation here:
https://www.useloom.com/share/ea090f3aa8fc4e59802adc2141b4d42e

Going forward make an element disappear, going backwards the element appears but with a sort of white flash.

**Comment by desandro** [comment] 2017-11-22 15:23
This looks like a wrap-around issue where there isn't enough content to cover the full width of the viewport. My recommendation is to disable wrapAround in the these scenarios.

Duplicate of #95

**Closed by desandro** 2017-11-22 15:23 UTC

**Comment by realchriswells** [comment] 2022-03-15 08:13
@desandro I'm experiencing this on v2.3.0. Is there a better work around than turning off the wrapAround, or a way to do it automatically in these situations on only relevant carousels?

**Comment by handiworknyc** [comment] 2022-12-15 00:29
There is a hilariously EASY solution for this.

Duplicate your slides, so instead of 3 slides, there are 6. Problem solved.
