### ISSUE TITLE
Broken pagination buttons illusion, due to a combination of options.

### ISSUE THREAD

**Issue by guanzo** [metafizzy/flickity#613] opened 2017-08-03 18:33 UTC
Please examine the jsfiddle.

**Test case:** https://jsfiddle.net/ezqvh900/1/

In my example, i have a blue outline that indicates the selected cell. If you press the next button, you can see the blue outline move right, however the carousel doesn't move, until the blue outline has reached the right side, (due to the "cellAlign: 'right'" option)

In my application, i do not have this blue outline. This would be the bottom carousel in my example.
When the user clicks the next button, he has to click it several times until the carousel begins to move, so it gives off the illusion that page buttons are somehow buggy. The easiest fix is to just add this outline, however i was wondering if there was a way within flickity to just move the carousel left/right, regardless of the selected cell or cellAlign.

**Comment by desandro** [comment] 2017-08-04 13:53
Duplicate of #177

**Comment by desandro** [comment] 2017-08-04 13:54
See https://github.com/metafizzy/flickity/issues/177#issuecomment-117680694

> I get what you're asking for. When multiple cells are visible or with 'contain': true, there can be areas when clicking the previous/next arrows won't move the slider. 
> 
> While the slider does not change, the selected cell does. This may be useful for accessibility, as it allows users to select a cell with buttons, rather than with mouse.
>
> So your request is valid, but it's important to keep previous & next arrows working consistently for accessibility.
> Try [groupCells](http://flickity.metafizzy.co/options.html#groupcells)

**Closed by desandro** 2017-08-04 13:53 UTC
