### ISSUE TITLE
Weird behaviour when there's not enough elements to show 

### ISSUE THREAD

**Issue by piotrkulpinski** [metafizzy/flickity#298] opened 2015-12-10 13:28 UTC
Hi,
I created a basic example showing what I'm talking about:
http://codepen.io/piotrkulpinski/pen/pgJaxK

As you probably see there's a weird issue with elements showing/hiding randomly on the slider.
Another thing is that they're right aligned even when `cellAlign` is at it's default - `center`

Is there any workaround I could use to make this more usable for various element count?
Thanks

**Comment by desandro** [comment] 2015-12-10 14:32
Thank you for submitting this issue. This is a duplicate of https://github.com/metafizzy/flickity/issues/95#issuecomment-86124653

> Thanks for this feature request. Yes, this could be helpful. But I feel this is an edge case. Either your content works with wrapAround, or it doesn't. Catering to both use cases could be cumbersome.

**Closed by desandro** 2015-12-10 14:32 UTC

**Comment by piotrkulpinski** [comment] 2015-12-10 14:35
Hi @desandro,
thanks for your response.

I don't think this is an edge case seeing so many people asking for it.
I think it would be good to at least center the items as they should be and disable sliding totally when there's not enough elements.
