### ISSUE TITLE
When focussing away and back from tab the autoplay skips.

### ISSUE THREAD

**Issue by notflip** [metafizzy/flickity#18] opened 2015-01-28 14:03 UTC
When you focus away and or back in a tab ( chrome for windows ) the autoplay seems to skip the time and or return all the way to the front.

Great plugin!

**Comment by desandro** [comment] 2015-01-28 14:12
Yes it does. Thanks for reporting this bug. Closing as a duplicate of #6. This will be resolved in the next release of Flickity.

**Closed by desandro** 2015-01-28 14:12 UTC
