### ISSUE TITLE
Won't initialize properly when display: none

### ISSUE THREAD

**Issue by jasonwbullok** [metafizzy/flickity#73] opened 2015-03-04 22:20 UTC
When a flickity gallery is initialized at display: none then toggled to display: block, the gallery won't function properly. Explicitly calling flickity("resize") after display: block is toggled will resolve the issue, but it seems like it should do this natively. 

Uncomment line 15 of the JS in the following pen to see the workaround:

http://codepen.io/jasonwbullok/pen/LEBrXq

**Comment by desandro** [comment] 2015-03-05 03:28
Thanks for providing the test case! Closing here as a duplicate of #65. I'll provide an answer there.

**Closed by desandro** 2015-03-05 03:28 UTC

**Comment by awgul** [comment] 2020-05-08 13:09
@desandro And how about when the Flickity is enabled via `watchCss` ?
So slider is in a container that has `display:none` and on a click, I show the slider but only on mobile screens and on the desktop I disable the slider.
