### ISSUE TITLE
.flickity-viewport height calculation

### ISSUE THREAD

**Issue by mdmoreau** [metafizzy/flickity#101] opened 2015-03-31 19:29 UTC
Do you think it would be a good idea to have Flickity remove the inline style height on .flickity-viewport before recalculating it?  Right now if you use min-height: 100% on individual slides with variable height, they'll be correctly set initially, but if the elements decrease in height Flickity won't adjust the viewport size down, so you end up with slides that are much taller than necessary.

It'd be nice to be able to add a background to the individual slides that will span the entire height of the container with the use of min-height: 100%.  I'd be happy to take a crack at it - seems simple enough - but didn't know if it was something you'd want to add.

**Comment by desandro** [comment] 2015-04-01 00:26
Have you tried disabling gallery height with [`setGallerySize`](http://flickity.metafizzy.co/options.html#setgallerysize)?

**Comment by mdmoreau** [comment] 2015-04-01 04:17
Yeah I tried that but then the gallery has no height - seems like it would work if you wanted to specify a fixed height though.

What I was trying to do was use Flickity to calculate the tallest element height (which it currently does) and leverage that value for the absolutely positioned slides inside the container with min-height: 100%.  That way you can have slides that have fully flexible heights while all getting the height of the tallest slide.  This is useful if you want to have slides with varying amounts of content but have them appear consistent in size if each has a background.

I was able to add a quick fix by applying ``$(this).css('height', '');`` to the .flickity-viewport on window resize whenever the current window width != the previous window width.  Doing it on any resize caused some issues on mobile devices, but this seems to be working okay for me so far.

http://codepen.io/desandro/pen/ZYvemV shows the slides with different heights, visible through the gray background.  If you add min-height: 100% to the gallery-cell, you can see how they all match up now - http://codepen.io/anon/pen/zxXqXg.  It works fine if the height is scaling down on resize, but if it's increasing then you can see how it never readjusts.

**Comment by desandro** [comment] 2015-04-01 14:16
Sounds like a duplicate of Adaptive Height. Closing here. Follow along at #11

**Closed by desandro** 2015-04-01 14:16 UTC
