### ISSUE TITLE
very slow continuous movement

### ISSUE THREAD

**Issue by nokiko** [metafizzy/flickity#132] opened 2015-05-06 14:04 UTC
Is the an option to realy slow down the speed of the slider so that when we have autoplay:1 that instead of the too fast  speed it is now that w can get a very nice slow continuous movement

**Comment by desandro** [comment] 2015-05-06 17:33
Closing as a duplicate of #77. Add your +1 there! :fried_shrimp:

**Closed by desandro** 2015-05-06 17:33 UTC
