### ISSUE TITLE
Input fields on mobile devices

### ISSUE THREAD

**Issue by urshofer** [metafizzy/flickity#405] opened 2016-06-24 09:15 UTC
Hi

I'm referencing to this issue:
https://github.com/metafizzy/flickity/issues/105

I'm not sure if this is really resolved. I'm using flickity 1.2.1, and tapping on input fields on my iphone6 does not open the keyboard. I'm currently fixing this behaviour by throwing an exception on static click if the input is tapped.

```
    FlickityService.get(id).then(function(f){
      f.instance.on('staticClick', (event) => {
        if (event.target.nodeName === "INPUT" && global.isMobile()) {
          throw new Error("Forcing Stop Here!");
        }
      });
    });
```

Whereas the ```isMobile()``` function returns true if the script is executed on a mobile device.

Note I'm using flickity within an angular app, but I don't think that the issue is related to angular.

**Comment by desandro** [comment] 2016-08-12 19:12
I was not able to reproduce this issue in Flickity v2.0.2. Try updating to the latest! I'm closing this as fixed.

**Closed by desandro** 2016-08-12 19:12 UTC
Labels: under investigation
