### ISSUE TITLE
Animations still run when browser window is inactive

### ISSUE THREAD

**Issue by gergelypap** [metafizzy/flickity#64] opened 2015-02-25 14:05 UTC
When the current window is inactive (e.g. the user switched to another tab), the animation should not run at all. Upon switching back, all the "queued" animations run at once.

See: http://www.paulirish.com/2011/requestanimationframe-for-smart-animating/

**Comment by desandro** [comment] 2015-02-25 17:44
Hi! Thanks for this feedback.

Flickity already does use [requestAnimationFrame for its animation](https://github.com/metafizzy/flickity/blob/v0.3.1/js/animate.js#L97), so we're good there.

This sounds like a duplicate of #6, where `autoPlay` will keep advancing when the tab/window is inactive.

Can you confirm:

1. Is this an `autoPlay` bug, or a general animation bug?
2. What browser are you experiencing this bug in?

**Comment by desandro** [comment] 2015-03-11 15:53
Closing as OP did not provide clarification.

**Closed by desandro** 2015-03-11 15:53 UTC

**Comment by gergelypap** [comment] 2015-03-13 08:59
Sorry, for being late and not actually checking the code for requestAnimationFrame. I'm experiencing this in Chrome. Yes it sounds like #6, so leave this closed.
