### ISSUE TITLE
Add class to cell closest to selected alignment at any time

### ISSUE THREAD

**Issue by FreshDoc** [metafizzy/flickity#54] opened 2015-02-16 12:07 UTC
Slide doesn't selected during swype. It selected after swype. If I do swype I can't see which slide will be selected when I detach a finger from a touch screen.

**Comment by desandro** [comment] 2015-02-16 12:36
Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/contributing.md#submitting-issues).

**Comment by madebydominick** [comment] 2015-02-17 12:34
Built a reduced test case [here](http://codepen.io/madebydominick/pen/NPYWJW) to replicate this issue. It is the case. The `is-selected` class doesn't move to the relevant cell until after the finger is lifted off the screen. I'm guessing due to being linked to `touchend`?

**Comment by desandro** [comment] 2015-02-17 13:22
@madebydominick thanks for the CodePen

This cell selection behavior is by design. A selected cell is not the one closest to the selected alignment, it is the one that will end up at the selected alignment. This allows users to flick past a cell, or move forward, then back to a previous cell. There's no way to know what cell will be selected until after the drag (or swipe) has ended.

It sounds like what you're looking for is an additional selected class, that selects the cell closest to the selected alignment at any time. If others would like to see this feature added, please **+1** this issue.

**Comment by wgstjf** [comment] 2015-03-03 19:02
Hi there,

Just found this and absolutely loving it so thanks!

I am struggling with one thing though.  I have a slider that effectively has 3 is-selected slides at a time, the rest are (through css) set to 0.5 opacity.  I can target the is-selected slide wrapper to apply opacity of 1 but can't figure out how to effectively target the preceding and following slide to also make them full opaque.  Any help would be greatly appreciated.  

Did try the following to apply my own class of 'is-active' but firstly, doesn't seem to target the neighbouring slides correctly and secondly not sure how to make this seamless... :-)

```javascript
$gallery.on( 'cellSelect', function() {
    var selectedSlide = flkty.selectedIndex;
    var previousSlide = selectedSlide-1;
    var nextSlide = selectedSlide+1;
    $('.applications-slider').removeClass('is-active');
    $( ".slide-wrapper" ).eq( previousSlide ).addClass('is-active');
    $( ".slide-wrapper" ).eq(selectedSlide).addClass('is-active');
  });
```

Cheers,

Will

**Comment by desandro** [comment] 2015-03-03 22:18
@wgstjf This sounds like a separate issue. I've deleted your comment here and moved discussion to #69

**Comment by MeMyselfI** [comment] 2015-06-09 16:15
I do need this feature too, having the .is-selected element changing during swiping.

**Comment by desandro** [comment] 2015-08-31 15:04
See my solution for adding `is-previous` and `is-next` classes to the previous and next cells: https://github.com/metafizzy/flickity/pull/227#issuecomment-135107460

Closing this issue here. Keep discussion to 227

**Closed by desandro** 2015-08-31 15:04 UTC
Labels: feature request, feedback welcome

**Comment by MeMyselfI** [comment] 2015-08-31 16:27
I'm sorry, I don't see how these to issues are related to each other. What we asked for is a .selected class for the item that will probably be selected (so the one that's in the middle) DURING SWIPING. The .is-previous and .is-next are set AFTER THE SWIPING. That doesn't help.
