### ISSUE TITLE
Mobile Safari 9.0 touch events not working.

### ISSUE THREAD

**Issue by stephan-v** [metafizzy/flickity#830] opened 2018-09-06 10:13 UTC
The slider works perfectly fine and the buttons also work, yet touch events do not seem to be working at all.

I have tested this on a iPad 4 that is running Safari Mobile 9.0.

According to the browser support this should be working fine:

> Flickity v2.1 supports Chrome 33+, Safari 9+ (mobile & desktop), IE11+, Edge 12+, and Firefox 23+.

There do not seem to be any error messages.

Touch also does not work when I view the examples of the Flickity website so this is not just related to my own code.

**Comment by LucAwater** [comment] 2018-09-14 13:20
Same here, tested on a iPad mini. I too opened up the Flickity site, and sliders didn't respond to touch there either.

**Comment by MezMerrit** [comment] 2018-09-19 12:16
Not sure if this is helpful or not, but I just had a few dozen clients go test this page: [http://ozcoolies.com/test/swipe.htm](url) hoping to snag a Blackberry test. While I didn't get any Blackberry users, I did get positive feedback from users of iPad, iPadX, iPhone 7, 8 and Plus, Samsung, HTC10 and Sony... the last two were a pleasant surprise. Anyway, hope that helps to narrow down the source of the issue. Good luck!

**Comment by desandro** [comment] 2018-09-20 19:36
Thanks for reporting this issue. I'll have to take a look.

**Comment by hinok** [comment] 2018-11-21 08:51
@stephan-v @LucAwater Could you make a test using newest Flickity from `master` branch? I think that this should resolve the issue https://github.com/metafizzy/flickity/commit/ab0762406e961219c13a0b776a7806f5ff0a3b39

**Comment by desandro** [comment] 2018-11-21 14:18
Related #842

**Comment by desandro** [comment] 2019-01-11 16:20
Closing as a duplicate of #842

**Closed by desandro** 2019-01-11 16:20 UTC
Labels: under investigation
