### ISSUE TITLE
autoPlay doesn't resume after interactions when mouse leaves carousel

### ISSUE THREAD

**Issue by thelucid** [metafizzy/flickity#769] opened 2018-05-24 15:01 UTC
The example on the showcase site illustrates this problem. If you interact with the slider and then mouse out of the area, autoPlay fails to resume.

**Test case:** https://flickity.metafizzy.co/options.html#autoplay

**Comment by desandro** [comment] 2018-05-26 20:15
autoPlay is designed to stop and stay stopped any time the user interacts with the carousel. This gives user control and does not take it away from the user. On mobile, there is no hover event so there is no way to detect when a cursor has exited the carousel.

If you wish to implement that behavior, you can do so with your own JS and the [Flickity API](https://flickity.metafizzy.co/api.html).

---

Closing as a duplicate of #734

**Closed by desandro** 2018-05-26 20:15 UTC
