### ISSUE TITLE
Scroll more than 1 item

### ISSUE THREAD

**Issue by manlioma** [metafizzy/flickity#112] opened 2015-04-16 10:24 UTC
Hi, is it possibile to select how many items scroll a time ?

In demos i see only scroll 1 item a time.

Let me know
thanx!

**Comment by desandro** [comment] 2015-04-16 18:28
Currently, no. Sounds like you are asking for slide by group. Closing as a duplicate of #22.

**Closed by desandro** 2015-04-16 18:28 UTC
