### ISSUE TITLE
Not center selected cell when 2 cells with wrapAround option

### ISSUE THREAD

**Issue by t-walker-wei** [metafizzy/flickity#1091] opened 2020-08-12 01:31 UTC
**Test case:** https://codepen.io/t-walker-wei/pen/oNxjMLM

Also the style not correct when have 3 cells.

**Comment by produktive** [comment] 2020-08-24 14:23
I am also having this problem. Bump.

**Comment by produktive** [comment] 2020-10-12 16:18
Any updates on this?

**Comment by desandro** [comment] 2021-01-13 12:29
Closing as a duplicate of #809

**Closed by desandro** 2021-01-13 12:29 UTC
