### ISSUE TITLE
Flickity still hidden after displaying

### ISSUE THREAD

**Issue by isbara** [metafizzy/flickity#150] opened 2015-05-30 13:44 UTC
Hi, maybe this is not total related to flickity but I am using Jquery to "display:none to block" on parent main-gallery div. But images are not shown. Onyl shown after resizing the browser and inspect element.

``` html
<div id="gnc2"class="row">
  <div class="col s3 offset-s1">

    <div class="thumbnail">
      <img src="galeri/gizemler/1.jpg" alt="Gizemler">
      <div class="caption">
        <h5 class="center-align">Gizemler</h5>
        <p class="center-align">Serideki mitler, gizemler</p>
        <p class="center-align"><a id="nbg2" class="waves-effect waves-light btn">Ateşle</a></p>
      </div>
    </div>

  </div>
</div>

<div id="nbg1">
  <h5 class="center-align">One Piece Gizemler</h5>
  <div class="main-gallery">
    <div class="gallery-cell"><img src="galeri/gizemler/1.jpg"/></div>
    <div class="gallery-cell"><img src="galeri/gizemler/2.jpg"/></div>
    <div class="gallery-cell"><img src="galeri/gizemler/3.jpg"/></div>
  </div>
</div>
```

``` js
$('.main-gallery').flickity({
    // options
    cellAlign: 'left',
    contain: true
  });

$(document).ready(function() {
  $('#nbg2').click(function() {
    $("#gnc2").css("display","none");
    $("#nbg1").css("display","block");
  });
});
```

**Comment by desandro** [comment] 2015-06-02 20:28
If Flickity is initialized while hidden, it will need its [`resize` method](http://flickity.metafizzy.co/api.html#resize) to be triggered. See demo http://codepen.io/desandro/pen/eNvdoo

---

For your code, bring the flickity code inside `$(document).ready()`

``` js
$(document).ready(function() {
  var $mainGallery = $('.main-gallery').flickity({
    // options
    cellAlign: 'left',
    contain: true
  });


  $('#nbg2').click(function() {
    $("#gnc2").css("display","none");
    $("#nbg1").css("display","block");
    // resize flickity after being shown
    $mainGallery.flickity('resize');
  });
});
```

**Comment by desandro** [comment] 2015-06-02 20:43
Closing this issue as a duplicate of #65. See solution there

**Closed by desandro** 2015-06-02 20:43 UTC
Labels: question

**Comment by JacobGPD** [comment] 2018-04-11 00:08
Hi @desandro,

I'm having the same issue here. Can you please explain further where to paste this:

$(document).ready(function() {
  var $mainGallery = $('.main-gallery').flickity({
    // options
    cellAlign: 'left',
    contain: true
  });


  $('#nbg2').click(function() {
    $("#gnc2").css("display","none");
    $("#nbg1").css("display","block");
    // resize flickity after being shown
    $mainGallery.flickity('resize');
  });
});


Thanks!
