### ISSUE TITLE
Slide wrapping issue - slide appears to wrap too early

### ISSUE THREAD

**Issue by cameroncowden** [metafizzy/flickity#625] opened 2017-08-29 19:21 UTC
Hi,
Firstly - thanks for maintaining this, it's been a huge help. 

I'm using Flickity-sync to sync two sliders for a product image slider and thumbnail nav.

The issue I'm having is that it appears to try to wrap too soon, and take the slide that should be in position one (furthest left), and putting it on the right side.

**Test Case**: https://codepen.io/anon/pen/wqQewq

**Comment by desandro** [comment] 2017-08-31 12:52
Thanks for reporting this issue. This is a duplicate of #95 

Sorry, but I won't be able to fix this one. From https://github.com/metafizzy/flickity/issues/95#issuecomment-246213137

> The only fix is to duplicate content so that it fills the container. Not only will this add complexity, but there's all these issues that arise when you start cloning nodes — events may not work right, duplicated stuff doesn't get copied correctly, CSS stuff may break.

**Closed by desandro** 2017-08-31 12:52 UTC
