### ISSUE TITLE
cellSelect + settle are fired when manipulating cells

### ISSUE THREAD

**Issue by pseidemann** [metafizzy/flickity#142] opened 2015-05-20 18:43 UTC
hello,

when I prepend/append/insert/remove cells, cellSelect + settle are fired, which I don't expect.

this bug makes it impossible to add cells dynamically in the cellSelect/settle event listener (which was fired by a previous select() call). the listener will be called twice.

test case: http://codepen.io/anon/pen/Kpgzqg

**Comment by brandondove** [comment] 2015-05-26 17:33
+1 I'm getting this too.

**Comment by desandro** [comment] 2016-03-18 14:28
Thanks for reporting this issue. Yes, this is how Flickity operates. After changing the cells, Flickity triggers `select` so it can properly reposition cells, and have a cell selected. I'd say it's a feature, not a bug :grin:. 

It's a been 10 months and this issue has been mostly quiet. Closing. Thanks again for chiming in! :strawberry:

**Closed by desandro** 2016-03-18 14:28 UTC

**Comment by leo-coco** [comment] 2016-09-29 01:02
Hello,

I'd like to reopen that discussion. I would like to append dynamically some slides when the last slide of the current carousel is reached. I was thinking to insert some slides on the event ''settle" but it creates me a infinite loop. Any one has a solution for that ?

Thank you

**Comment by jsbase** [comment] 2020-02-10 21:09
that's pretty uncool, because i can trigger a reposition cell method by myself
maybe u could add a boolean paramter to the append method which not triggers the select
