### ISSUE TITLE
Flickity Carousels don't "flick" easily in iOS 13

### ISSUE THREAD

**Issue by babysteps** [metafizzy/flickity#992] opened 2019-10-18 21:27 UTC
You can recreate this easily going to the Flickity homepage on an iPhone running iOS 13.  You will see that trying to flick through the carousel doesn't always take you to the next slide.  Then it will get stuck completely for a few moments.

**Comment by mellinger** [comment] 2019-10-21 04:11
+1

**Comment by babysteps** [comment] 2019-10-25 18:49
thank you.  i implemented @bakura10's fix and that seems to help for now.  hoping that @desandro will upgrade the script with a proper fix soon.

**Comment by desandro** [comment] 2020-05-14 17:25
Closing as a duplicate of #1009

**Closed by desandro** 2020-05-14 17:25 UTC
