### ISSUE TITLE
Release 2.0.6 breaks vertical touch scrolling in Chrome. 

### ISSUE THREAD

**Issue by marett** [metafizzy/flickity#560] opened 2017-05-17 05:50 UTC
Unable to scroll vertically past a carousel on Android Chrome and Desktop Chrome (using emulation in developer tools). Spent some time trying to troubleshoot this issue. 
Ultimately just tried reverting to 2.0.5 which resolved the issue. 

Test these two links in your Android Chrome browser:

**2.0.6**: Can't touch & drag on the carousel and scroll vertically. 
http://codepen.io/nivens/full/pPZBRV/

**2.0.5**: Vertical scrolling works fine.
http://codepen.io/nivens/full/BRPEWZ/

**Comment by desandro** [comment] 2017-05-17 14:30
Thank you for reporting this bug! Looks like this is caused by an over-zealous `touch-action: none` that was part of Unidragger v2.2.0. I'll revert this change in a patch

**Comment by simeydotme** [comment] 2017-05-23 07:51
hey @desandro :)
I feel dirty to even think about writing this... but...

Is there any word on when `2.0.7` to fix this regression will drop?; I'm trying to decide if I go in to bower to fix the version at `#2.0.5` or leave it at `~2.0.0` :)

_apologies and thanks_

**Comment by desandro** [comment] 2017-05-23 13:04
Ah! Sorry for the delay. v2.0.7 has been released with fix for touchAction.

**Closed** 2017-05-23 13:03 UTC

**Comment by simeydotme** [comment] 2017-05-24 07:23
Hey, Apologies @desandro ... first thanks for the fast response... but I've tested this now on Android (chrome) and find that the vertical scrolling works as expected 😄  -- But I also find that horizontal swiping is busted. Arrow/Navigation is working, but swiping is busted with some weird glitchy behaviour (skipping slides and then reverting back to the original). 😢 

probably all relates back to the damned passive touch handlers, but is there a chance to look in to that? I now going to roll back to `2.0.5` and lock it there 👍

**Comment by desandro** [comment] 2017-05-24 14:50
@simeydotme Sounds similar to #540

**Comment by davidcraigmyle** [comment] 2017-06-15 15:10
Had the same problem here, think it is either an updated version of unidragger or unipointer. If you use an older version of these it will work (I went back to 2.0.3 of flickity and 2.1.0 of both unidragger and unipointer)

**Comment by desandro** [comment] 2017-06-16 19:42
@davidcraigmyle  See https://github.com/metafizzy/flickity/issues/540#issuecomment-306210742
