### ISSUE TITLE
Dynamic height?

### ISSUE THREAD

**Issue by notflip** [metafizzy/flickity#72] opened 2015-03-04 15:20 UTC
Hi, 

Is it possible to have the content auto-scaled in height when there's overflow? 
and the content is dynamically loaded, so the height changes with .ajax requests that fill the content

Thanks

**Comment by notflip** [comment] 2015-03-04 15:50
I found the solution,

After every AJAX request i hit

    $gallery.flickity('reloadCells')

**Comment by notflip** [comment] 2015-03-05 10:22
I managed to get the desired result by calling

    $gallery.flickity('reloadCells');

But sometimes the height doesn't make sense at all. How is this computed? are there any other methods I can use to set the height dynamically?

thanks

**Comment by desandro** [comment] 2015-03-05 12:44
The height is based on the maximum height of the cells. `reloadCells` should update the height of the gallery accordingly. If you're running into a possible bug, could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by notflip** [comment] 2015-03-05 12:45
Hi! Thanks for your answer, I was wondering if it's possible to have the slider rescaled for every slide. So if the slide is smaller, that it rescales it..Instead of giving the highest height to every cell?

Thank you!

**Comment by desandro** [comment] 2015-03-05 12:51
Ah, in that case, that would be a feature request. A duplicate of #11. Closing here, follow there!

**Closed by desandro** 2015-03-05 12:51 UTC
