### ISSUE TITLE
WrapAround issue when only one slide

### ISSUE THREAD

**Issue by sky93** [metafizzy/flickity#1022] opened 2020-02-10 18:52 UTC
`wrapAround: true` option doesn't work as expected when we have only one slider.

**Test case:** https://codepen.io/sky93/pen/mdJJwbv

**Comment by clarknelson** [comment] 2020-02-10 21:06
seems as expected to me, what you are expecting?

**Comment by sky93** [comment] 2020-02-13 10:56
Slider should always be visible even when swiped. I want to have infinite scroll effect just like when we have more than one slider.

**Comment by clarknelson** [comment] 2020-02-13 18:02
![image](https://user-images.githubusercontent.com/4106671/74464154-a759f300-4e58-11ea-8475-a4e892796005.png)

I am seeing the single image fine. not sure how a slide would slide to itself or why you would want that.

**Comment by desandro** [comment] 2020-05-14 15:26
I'm closing this issue as a duplicate of #809. It may not be the exact solution you're looking for, but it's close enough.

**Closed by desandro** 2020-05-14 15:26 UTC
