### ISSUE TITLE
[Feature Request] - Further lazyloading options

### ISSUE THREAD

**Issue by nicholas-c** [metafizzy/flickity#175] opened 2015-06-29 09:44 UTC
Hey, So as discussed in my other feature request #173  - It would be nice to be able to specify other images to load based on viewport size - 
"data-flickity-lazyload-sml
data-flickity-lazyload-med
data-flickity-lazyload-lrg" 

that would be an example usage, I'm willing to put a PR together for this if people feel it's wanted? :)

**Comment by StephenRance** [comment] 2015-06-29 09:59
+1

Ideally we don't want to be loading in large images for smaller viewports.

**Comment by desandro** [comment] 2015-06-29 13:20
Thanks for this feature request. Rather that solve this with Flickity, I feel this should be handled by something like `<picture>` or `srcset`. I'm closing this as a duplicate of #173

**Closed by desandro** 2015-06-29 13:20 UTC

**Comment by nicholas-c** [comment] 2015-06-29 16:16
@desandro - Picture and srcset both have wildly low support certainly in IE and safari - http://caniuse.com/#search=picture && http://caniuse.com/#search=srcset

**Comment by hi-im-si** [comment] 2015-06-29 19:59
I agree with @nicholas-c, I don't see `<srcset>` and `<picture>` being in a state where they can be used completely in production at this moment in time especially where there is the need for supporting browsers like Safari, iOS and IE fully. We in turn end up using polyfills to provide necessary fallbacks which in turn is costly. Having these features built into flickity are most certainly needed for the now and the forthcoming future!

As a suggestion, having a similar syntax to how the [BBC's Imager](https://github.com/BBC-News/Imager.js/) works would work nicely.

```
var flky = new Flickity( '.gallery', {
     availableWidths: [200, 260, 320, 600]
});
```

+1 @nicholas-c
