### ISSUE TITLE
Option to duplicate first and last items 

### ISSUE THREAD

**Issue by Ch3Pz** [metafizzy/flickity#737] opened 2018-04-10 02:44 UTC
Hi, I really love this plugin however I'm having issue when the number of slides displayed is the same as the total number of slides. At some point, the first / last items are not showing due to it's positioning. I remember some other plugin has accomplished a way to do this by adding an option to 'duplicate first and last items'. 

Many Thanks!

**Test case:** https://codepen.io/desandro/pen/azqbop

**Comment by desandro** [comment] 2018-04-10 12:57
Sounds like a duplicate of #95. Sorry Flickity will not support this feature. See my reasoning at https://github.com/metafizzy/flickity/issues/95#issuecomment-246213137

**Closed by desandro** 2018-04-10 12:57 UTC
