### ISSUE TITLE
freeScroll carousel adjusts the position of cells when scrolling down the page

### ISSUE THREAD

**Issue by dangelion** [metafizzy/flickity#548] opened 2017-04-27 17:17 UTC
Free scroll is really really awesome but it has an horrible behaviour: after scrolling horizontally the cells, if you scroll down (or up) the page you'll see the cells repositioning with a "jump". The result is a carousel that seems buggy!

Here a video recording of the issue: https://youtu.be/YE2fqFz6u00 
Check the video: I scrolled the cells and let them there (cells 2 and 3 visible), then I scroll the page down and you see the carousel repositioning the cell 3 at the center.

I get this behaviour both on iPhone and Android.

Is there a way to solve? Thanks

p.s. already said that freeScroll is awesome? :)

**Comment by desandro** [comment] 2017-05-02 13:12
Thanks for reporting this bug. Hmm, this is real tricky one as I'm not able to reproduce with every carousel flick + page scroll. I'm not sure if this one is fixable.

**Comment by dangelion** [comment] 2017-05-02 16:15
> I'm not able to reproduce with every carousel flick + page scroll

You can reproduce it with this procedure:

1. From a smartphone navigate to http://flickity.metafizzy.co/#feature-showcase on "freeScroll" example
2. Drag the cells and place them as the gap between two cells is nearly at the center of the viewport
3. Scroll down (or up) the page => cells repositioning
4. Again, drag the cells and place them as the gap between two cells is nearly at the center of the viewport
5. If at point 3 you get cells repositioning by scrolling the page **down**, now scroll the page **up** (otherwise scroll the page down) => cells repositioning
6. Repeat from point 2

**Comment by desandro** [comment] 2018-02-09 20:13
No one else has chimed in, so I'm going to close this one as is. Please follow up if you'd like me to give this another look.

**Closed by desandro** 2018-02-09 20:13 UTC
Labels: bug
