### ISSUE TITLE
Uncaught TypeError: this._dragPointerDown is not a function error

### ISSUE THREAD

**Issue by howells** [metafizzy/flickity#724] opened 2018-03-28 08:37 UTC
Frustratingly, I can't reproduce a test case for this error I'm seeing when trying to drag a flickity instance, because I can't replicate it at all apart from on one project: it works perfectly elsewhere with the same setup. 

The slideshow is in a React app but so are others where I don't see this error, so that shouldn't be the issue at all.

What could possibly cause this error do you think?

Full error:

```
drag.js?f52b:175 Uncaught TypeError: this._dragPointerDown is not a function
    at Flickity.proto._pointerDownDefault (drag.js?f52b:175)
    at Flickity.proto.pointerDown (drag.js?f52b:171)
    at Flickity.proto._pointerDown (unipointer.js?cbf6:128)
    at Flickity.proto.onpointerdown (unipointer.js?cbf6:107)
    at Flickity.proto.handleEvent (unipointer.js?cbf6:77)
```

**Comment by aryehraber** [comment] 2018-03-28 10:39
Running into this too... I use Flickity in almost every project and not seen this error until today.

Perhaps a dependency is broken because pulling in a previous release still renders the same error.

**Comment by aryehraber** [comment] 2018-03-28 10:42
I just tried using the CDN version instead of pulling in through NPM and the latest version works as expected — issue is most likely caused by a dependency.

Adding this before own script will fix temporarily:
```
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
```

**Comment by Borange** [comment] 2018-03-28 10:59
Got the same problem. Seems to be in the unidragger dependincy, the method _dragPointerDown has been removed.

https://github.com/metafizzy/unidragger/commit/6263d8fa8b64e522045aacf6f1954653df2f20ee#diff-bdf3066081d472b39cdd3d8bb82dc2d0

**Comment by howells** [comment] 2018-03-28 12:02
@aryehraber strangely that doesn't help in my case

**Comment by Borange** [comment] 2018-03-28 12:08
I found the problem and fixed it on my local installation and got it to work again. I made a pull request for it in the unidragger repository. Hopefully it will be approved and updated soon :)

**Comment by macdaddyaz** [comment] 2018-03-28 15:09
In the meantime, I locked the unidragger dependency to version 2.2.3, and that works.

package.json:
```
    "resolutions": {
      "unidragger": "2.2.3"
    }
```

**Comment by desandro** [comment] 2018-03-28 16:26
Looks like I introduced breaking changes in unidragger 2.3. I'll have a fix up in a couple days. Sorry for the hassle!

As mentioned ☝️ you can either use `flickity.pkgd.js` or specify `unidragger: 2.2` as a dependency.

**Comment by raphaelokon** [comment] 2018-03-29 11:36
@desandro Can you post steps to mitigate this? My automatic builds fail because of this.

**Comment by aryehraber** [comment] 2018-03-29 19:24
Thanks for the quick fix @desandro!

**Comment by aryehraber** [comment] 2018-03-29 19:25
p.s. I can confirm the latest version works when installed via npm

**Comment by ChristophJeworutzki** [comment] 2018-03-29 21:08
Works like a charm! Thank you for the quick fix! @desandro

**Comment by michaeljpowell** [comment] 2018-03-30 21:58
Works great! Thanks, @desandro

**Comment by schellenbergk** [comment] 2018-03-30 23:54
Thanks! @desandro it works here too :)

**Comment by desandro** [comment] 2018-03-31 01:55
Thanks for the confirmations. I'm closing this issue as resolved.

**Closed by desandro** 2018-03-31 01:55 UTC
Labels: bug

**Comment by jpannone** [comment] 2019-01-18 20:52
I am still seeing this issue installing flickity@2.1.2 via NPM.

I am able to resolve by installing unidragger@2.2.3 instead of 2.3.0

**Comment by jetpack3331** [comment] 2019-02-07 17:06
It's not resolved @desandro .
It's still happening also on the version v2.1.1
