### ISSUE TITLE
Slider does not scroll smoothly on mobile

### ISSUE THREAD

**Issue by UzairSalman** [metafizzy/flickity#998] opened 2019-10-30 22:09 UTC
I've been using this plugin through Flatsome Theme for woocommerce. 
However I am having a huge issue regarding the swiping right/left on mobile to change the slider on main homepage. 

Link: dablew.pk 
(view on mobile, the main slider)

Please tell me a fix for this. Thanks

**Comment by fbnntt** [comment] 2019-11-01 14:21
I'm having the exact same issue. A fix for this would be great.

**Comment by benabbottnz** [comment] 2019-11-04 02:26
What kind of phone do you have? It scrolls smoothly for me.

**Comment by UzairSalman** [comment] 2019-11-04 10:56
I tried it using multiple android phones, its not scrolling smoothly.

**Comment by UzairSalman** [comment] 2019-11-04 11:24
I just tried it on iPhone 11 Pro Max and it wasn't sliding smoothly.

**Comment by XPOL555** [comment] 2019-11-06 11:52
Hi @UzairSalman this might be related to this https://github.com/metafizzy/flickity/issues/959 and also this https://github.com/metafizzy/flickity/issues/740

**Comment by desandro** [comment] 2020-05-14 17:47
Closing as a duplicate of #959

**Closed by desandro** 2020-05-14 17:47 UTC
