### ISSUE TITLE
Fade transition?

### ISSUE THREAD

**Issue by rawcreative** [metafizzy/flickity#26] opened 2015-01-29 17:00 UTC
While it's obvious that flickity is meant to be based on a sliding transition, I was curious if there's any plans on implementing an optional Fade based transition/animation instead of the slide? 

I would love to replace my current hand-rolled image galleries/carousels with flickity in my projects both personal and commercial, but many of them use fading transitions instead of sliding. I'd be more than happy to pre-pay for a commercial license/donate/whatever if it helps that get implemented.

**Comment by desandro** [comment] 2015-01-29 18:41
Hi! Thanks for this feedback. No, I do not have plans to add fade transitions to Flickity. This seems like a simple feature, but it would be complex to add. Flickity is designed to work with cells that are laid out next to one another.

If you would like to see this feature, **+1** this ticket.

If fade transition is a must have featured, I recommend [Slick](http://kenwheeler.github.io/slick/) by @kenwheeler

**Comment by hellojebus** [comment] 2015-02-21 01:24
This would definitely be a cool option. I've used Slick and it is a great alternative. I'll stick to Flickity in the meantime though.

**Comment by hydrotik** [comment] 2015-02-28 23:09
:+1: You might consider a feature comparison with Slick as it's a bit unclear what the justification would be to move from the MIT license of Slick to a commercial license with Flickity?

**Comment by desandro** [comment] 2015-02-28 23:16
After consideration, Flickity will not add fade animation. Flickity is all about sliding. Fade transitions are a different pattern that would require a lot of re-tooling. Use Slick or RoyalSlider instead.

**Comment by hydrotik** [comment] 2015-03-01 03:35
We have been using Slick for some time already. With the great experiences we have had with Isotope, we were excited and quick to explore moving to Flickity with the corporate license. Again, it would be nice to understand the difference between the two (and anything else that is comparable) in making a determination on what will ultimately add more value.

**Comment by hydrotik** [comment] 2015-03-01 03:47
Also thought I'd include this in this thread as you took the time to write a thoughtful post on the metafizzy site about the value of the product which I found after my previous comment.

http://metafizzy.co/blog/flickity-v1-released/

And a somewhat related thread on a previous license question https://github.com/metafizzy/flickity/issues/20

**Comment by FabianGabor** [comment] 2015-03-02 17:32
If it would be an option to set the slide transition time or completely disable the sliding, the fade animation could be easily solved with css opacity transitions, no need for jquery.

**Comment by wgstjf** [comment] 2015-03-04 08:26
+1 on the ability to fade even if it uses css as per @FabianGabor suggestion.  With that in place I know I would be able to achieve all my clients' site design requirements with one great 'slider'.

Cheers,

Will

**Comment by inlikealion** [comment] 2015-03-05 17:53
+1

**Comment by josephbergdoll** [comment] 2015-03-13 15:28
+1

**Comment by terkelg** [comment] 2015-03-16 15:02
+1

**Comment by StefanEndress** [comment] 2015-03-20 22:49
+1

**Comment by paul-straetmans** [comment] 2015-03-21 10:07
+1

**Comment by egr103** [comment] 2015-03-23 16:32
+1

**Comment by eikeco** [comment] 2015-06-05 12:34
+1

**Comment by aaronstezycki** [comment] 2015-07-08 14:04
+1

**Comment by aaronstezycki** [comment] 2015-07-10 13:37
So I've managed to hack around this, and it might be a 'omg don't do that' situation, but meh, I'm not bothered. Here's how I did it (CSS Only):

```
.flickity-slider{ transform: none !important; }
.slider__item{
    left: 0 !important;
   opacity: 0;
   transition: "opacity 0.3s ease-in-out";
}
.slider__item.is-selected{
    opacity: 1;
}

```
Voila

**Comment by eikeco** [comment] 2015-07-12 12:20
I have taken @aaronstezycki example and reproduced it here:
http://codepen.io/eikeco/full/MwGRKr

It certainly works but I would still recommend [Slick](http://kenwheeler.github.io/slick/) or [RoyalSlider](http://dimsemenov.com/plugins/royal-slider/) as @desandro mentioned in his initial reply.

That said, it's a good hack @aaronstezycki :)

**Comment by lmartins** [comment] 2015-07-29 11:04
Nice. @aaronstezycki suggestion seems like a viable solution for single item sliders.
Would love to have this feature built in in Flickity, so that I can use just one plugin for all my sliders. Will give this solution a go.

**Comment by dustinhorton** [comment] 2015-08-20 06:38
+1

**Comment by paulmasek** [comment] 2015-08-20 13:00
+1

**Comment by mdmoreau** [comment] 2015-10-07 20:30
The CSS trick seems to work really well @aaronstezycki - nice!  The only thing I noticed is that you'll probably want to add a `z-index: 1` to `.slider__item.is-selected` so you can interact with the active slide.

**Comment by eikeco** [comment] 2015-10-08 10:24
@mdmoreau I have updated the demo here: http://codepen.io/eikeco/pen/MwGRKr

I set hidden slides to have ```z-index: -1;``` and ```.is-selected``` to have ```z-index: 0;```. Setting ```.is-selected``` to ```z-index: 1``` covers the navigation items. See demo above.

Thanks for the tip :)

**Comment by mdmoreau** [comment] 2015-10-08 15:55
Looks good @eikeco - will probably have to adjust the z-index on a per project basis as adding a background to `.gallery` breaks that change and only using what I suggested messes with any overlapping nav.  Either way looks like a promising workaround generally - appreciate the discussion!

**Comment by samuelwill** [comment] 2016-03-01 19:40
+1

**Comment by TiagoDeSousa** [comment] 2016-03-28 14:17
+1

**Comment by Tumki** [comment] 2016-04-05 10:38
Thnx @eikeco Exactly what I needed. With a simple transition, you can even animate the text in and out:

http://codepen.io/Tumki/pen/JXOyvp

**Comment by JiveDig** [comment] 2016-09-08 19:20
+1

**Comment by onigetoc** [comment] 2016-12-03 02:26
+1

**Comment by mom6x** [comment] 2016-12-10 13:06
@eikeco or @aaronstezycki is it possible for the "autoPlay: true" option to work with this css? When I implement the css, the fade transition works great, but the autoplay stops working. Sorry, I'm really new to this!

**Comment by sebastianschrama** [comment] 2017-01-28 08:02
+ 1

**Comment by ricardovf** [comment] 2017-02-02 18:51
+1

**Comment by desandro** [comment] 2017-02-03 19:57
**Add a 👍  reaction** to show your support for this feature. Do not add +1 comments — They will be deleted. Subscribe to the issue using the button in the sidebar.

**Comment by JiveDig** [comment] 2017-02-03 21:56
Thumbs up added to the OP.

**Comment by dallanlee** [comment] 2017-03-27 23:22
I love Flickity for all of it's original capabilities. But I am also requesting this feature because on some projects I want a Flickity carousel to function as a traditional sliding carousel up to a certain breakpoint (1024px) where it would then transition with fading and not sliding. So I'd like both functionalities for a single carousel object. I moved from Slick carousel to Flickity a while ago even though Slick is good, Flickity is better and I only want to use Flickity in my projects. I hope this feature has enough demand to merit its implementation.

**Comment by maimairel** [comment] 2017-04-15 12:07
I really hope the fade feature added to Flickity making it the last plugin for showing/hiding items you'll ever need. Currently there's no plugin that controls the item sizes 100% via CSS. There are, but none of them has advanced features like Flickity. All other plugins controls the item sizes explicitly by specifying width/height on items.

**Comment by dallanlee** [comment] 2017-04-16 01:19
UPDATE: I've removed my thumbs up to the OP and no longer add my vote to wanting this feature added at the plugin level. CSS approaches, such as the ones exampled in previous comments here and variations of them, are acceptable solutions. I am able to even do a crossfade so that the transition between slides blends the two opacities together. This can also be controlled at media breakpoints and only requires CSS. I'm just posting this because I think the CSS approach is totally acceptable.

**Comment by callumflack** [comment] 2017-04-16 01:31
@dallanlee all CSS techniques I've seen have a flash. Have you got a technique that doesn't?

**Comment by dallanlee** [comment] 2017-04-16 22:35
@callumflack My development is currently just local so I'd have to create a Pen or something. I'll see if I can make some time.

**Comment by dallanlee** [comment] 2017-04-17 00:06
@callumflack So I'm not sure what flash you're talking about but here's a Pen of what I'm basically doing with the carousel (which slides on small screens and fades on medium-and-up screens) in a current project: http://codepen.io/dallanlee/pen/PmqEQE?editors=1100

**Comment by gingersoulrecords** [comment] 2017-06-13 17:58
@dallanlee In carousel fade transitions, the 'flash' is the brief moment when both elements (one fading out, the next fading in) are at 50% opacity, therefore allowing some 'light' from the background to show through and creating a brief flash. This is noticeable on lighter backgrounds. 

I've found few carousels that do this right. One is Patrick Kunka's EasyFader script which I forked here:

https://codepen.io/gingersoulrecords/pen/BZzEzR

To do this with Flickity, I think you'd need to set opacity values of hidden elements after slide transitions had been completed, and then manually transition them to 1 after their z-index jump. 

It's doable - but I'm struggling a little, going to keep trying. 

DB

**Comment by dallanlee** [comment] 2017-06-14 02:26
@gingersoulrecords I feel like that's design/CSS-related and not slider-function-related, if I'm understanding correctly. 

If you don't want white between transitions, you change the background color, which I'm sure you understand. But if we're talking about slides with images and you want the images to cross-fade and eliminate a flash of *any* background color, you set the CSS to do so with `z-index` and `opacity` transitions so that there's never less than 100% combined opacity between the images.

I've updated my Pen to demonstrate that fading can occur without ever seeing the background color of parent elements (when using cross fading on elements with colored backgrounds, be it block elements with the appropriate CSS or images). You can look at lines `210-221` in my SCSS. The z-index changes from 1 to 2 once active. And the transition function for the opacity is the same for all slides; except that the active slide starts without a delay—unlike the non-active slides. This ensures that the images have at least 100% combined opacity during the fade transition and therefore we don't see any background of the parent element(s). There is never less than 100% opacity between the two slides.

Let me know if I'm missing something!

Link to the Pen again: https://codepen.io/dallanlee/pen/VWKLXy?editors=0100

**Comment by gingersoulrecords** [comment] 2017-06-14 03:43
@dallanlee excellent work. I totally forgot about using animation-delay...

Could you apply your workaround to something simpler, like this pen?

https://codepen.io/eikeco/pen/MwGRKr

**Comment by dallanlee** [comment] 2017-06-14 09:47
@gingersoulrecords Fork: https://codepen.io/dallanlee/pen/GEjWpo

**Comment by gingersoulrecords** [comment] 2017-06-14 12:20
Very slick, I think that should take care of most people looking for a flash-free fade.

**Comment by gingersoulrecords** [comment] 2017-06-14 13:44
No pun intended there (slick).

**Comment by featherbelly** [comment] 2017-12-18 21:08
@dallanlee that is a great little solution!!! You never know when a client want to lose the slides and switch to fade!

**Comment by leenasekhar** [comment] 2018-01-16 10:02
@dallanlee Please help me with implementing the same in the case of a vertical carousel. I am using slick slider. I couldn't find examples on vertical carousels with fade in / fade out effects and disabled vertical movements of slides so far.

**Comment by dallanlee** [comment] 2018-01-17 05:38
@leenasekhar I don’t understand. You want a solution like this but for a Slick carousel implementation?

**Comment by leenasekhar** [comment] 2018-01-17 07:12
@dallanlee  Yes! You are right.

**Comment by dallanlee** [comment] 2018-01-18 00:04
@leenasekhar Sorry but I haven't used Slick in a couple years because of a couple limitations. If you have a CodePen for me to look at to get started, I may be able to find some time to tinker with it.

**Comment by desandro** [comment] 2018-03-12 15:14
I'm re-opening this issue to gain more feedback.

**Comment by gingersoulrecords** [comment] 2018-03-12 16:21
@desandro I've used @dallanlee 's solutions to construct a few instances of fading carousels (for things like testimonials on more fade-y, elegant layouts that don't want quick movements). What other kinds of feedback are you looking for?

**Comment by eikeco** [comment] 2018-03-12 16:43
@desandro here's a visual example of what I think we are asking for (based on @aaronstezycki solution): http://codepen.io/eikeco/full/MwGRKr

Of course, it's a hack. I'm not suggesting this is how you implement the feature.

**Comment by dallanlee** [comment] 2018-03-12 17:15
@desandro looking at the comments here from the past year, you'll already know my opinion on the matter, which hasn't really changed. If there were to be a JS option to change the carousel's interface type from moving/sliding to fading, I would still welcome it, but I'm not anxious for it.  

All it would need to do, IMO, is have no CSS `transform` on `.flickity-slider`, set the CSS of `.gallery-cell` to not have a `left` value, make `z-index: 1` and `opacity: 0` while `.gallery-cell.is-selected` has `z-index: 2` and `opacity: 1`. Which means `.flickity-previous-next-button` needs `z-index: 3`. Flickity could then have a starting default `transition` value on the `opacity` property that can easily be overwritten with the users own CSS. 

But honestly, this *hack* isn't a problem for me. Calling it a hack gives it a negative connotation. I don't think there's a problem with it other than having to use `!important` in my CSS to override Flickity's inline styles. 

Here's the basic demo you probably saw above where I implemented fading [https://codepen.io/dallanlee/pen/GEjWpo](https://codepen.io/dallanlee/pen/GEjWpo).

**Comment by desandro** [comment] 2018-03-13 15:54
@dallanlee Thanks for your input here. I appreciate your enthusiasm! This would be a bigger feature because it directly confronts Flickity's positioning behavior. Here are some of the questions I'll need to answer (in addition to the points you raised):

+ What about `groupCells`? 
+ What about `cellAlign`?
+ What about dragging? What about the `scroll` event? Does dragging incrementally change opacity moving from one slide to the next?
+ Should cells get `display: none` when they are completely hidden?
+ What happens when you remove a cell?

I've got ideas about how to address these. I think it can be done. But like I originally said, this is going to be a complex feature. If I'm going to do it, I'd like to do it right.

---

On top of that, the whole of Flickity is that it's **flickable**. It's is tactile, responsive to movement. Fade transitions with static positioning is antithesis to that. If you want a fade carousel, you don't need Flickity. You can build it mostly with CSS and some light JS.

This feature is just not my cup of tea. But there's been so much interest in it. So I'm mulling it over.

**Comment by dallanlee** [comment] 2018-03-13 17:15
@desandro Wow, very good points that I haven't given much thought to. I agree that Flickity isn't the right choice for a fade-only carousel. I've personally done it when the design calls for the same set of slides to be flicked on some screen sizes and faded on others. But I have been very narrow-sighted with the fade use cases based only on my specific needs. I'll take a back seat on this and see what others have to say before I provide more input 😳

**Comment by gingersoulrecords** [comment] 2018-03-13 17:34
The reason I liked @dallanlee 's fork was because other carousel plugins (slick, etc) have a 'flash' issue where, during a transition, two slides having opacity values less than 1 causes a 'flash' of the background color. Using his fork, I'm able to achieve a far more elegant 'dissolve' effect, but I do have to override CSS and make sure that my transition speed is quicker than the animation delay. 

Given the physics, grouping, and flickability intentions of Flickity, adding a fade option does feel forced. @desandro have you given any consideration to building a separate fading carousel plugin, if it's that simple? I'd use/buy it in a heartbeat.

**Comment by jan-dh** [comment] 2018-03-20 13:13
+1 on this one

**Comment by CHEWX** [comment] 2018-04-27 20:35
I get the concern here, however, in the read world, a developer doesn't think, "I need a slideshow that has a focus on being tactile and responsive" for my project. They usually go down the lines of, "I need a slideshow that is decent". 

Also, this library is usually put into websites, a full website, not just a single instance implementation, as such, web designs have variations of slideshows, should that mean the developer have various implementations of a slideshow plugin? I don't think so. Nor should it mean they implement Flickity for one variation and then custom code "with CSS and some light JS", a fade version, as you'd normally need more features than just fading, as per the Flickity API.

I think either, fade needs to be put in, just for the shear need for it (nearly 14k view on this — https://codepen.io/eikeco/pen/MwGRKr/) and I'd like to think the code would not bloat the plugin, or either a FAQ is added that specifies the correct hack implementation to use.

Essentially, people asking for fade, shouldn't be faced with "this slideshow isn't built for you" response. 

As such I'd like to hope this 3 year old thread could come to a decisive end :)

**Comment by gavin310** [comment] 2018-05-14 16:37
> What about dragging? What about the scroll event? Does dragging incrementally change opacity moving from one slide to the next?

@desandro It would be pretty cool if dragging would incrementally change the opacity. Or at least having that as an option.

**Comment by cmalven** [comment] 2018-10-24 22:35
Since it looks like you're looking for some feedback on this issue, here's my 2 cents…

I would _love_ to have either an official "fade" transition in Flickity, or an easy, officially-supported way to accomplish a fade transition using the API. Some of the solutions posted here work okay, but I'm hesitant to use anything that isn't officially supported and documented by Flickity for fear of it breaking in future updates.

Every project I ever work on has at least one slider, sometimes several of them. I strongly prefer the flexibility, documentation, stability, and API of Flickity over any other option. However, much of the time a slide transition doesn't make sense for the design/animation language of the project. I still want all of the great things Flickity brings to the table, but I have to settle for an alternative just because Flickity includes no supported way to create the experience I'm looking for.

Even worse is when I have _one_ slider experience on the site where Flickity absolutely is the best option, and another slider experience where it isn't. I'd have to be out of my mind to include two slider libraries, so usually that means I just don't use Flickity.

I understand the original thinking behind "Flickity is a _slider_ library, it shouldn't include other types of transitions", but this doesn't mesh with my thinking about these types of experiences, which is that they are collections of rotating content and the type of transition is just an implementation detail.

>  If you want a fade carousel, you don't need Flickity. You can build it mostly with CSS and some light JS.

Here's a short list of things Flickity provides that are separate from "flicking":

- Keyboard control
- Slide control UI
- Navigation for another flickity
- Disabling slideshow functionality at certain sizes using `watchCss`
- Grouping Cells
- Setting browser hash based on slide
- Automatically resizing based on content
- imagesLoaded support
- Fullscreen
- Full API for adding slides, removing slides, changing slide, getting current slide, etc.

Maybe most of those features in isolation aren't too big, but in aggregate that's a lot of functionality to get for free even if I have no interest in a flicking experience.

**Comment by mkstix6** [comment] 2018-11-24 13:36
**A scenario:**
On sites where we have designed a large, relaxed-fade-transition, hero-area on one page. But also sliding carousels of items on other pages (especially common in our mobile designs).

Rather than serving two libraries to achieve the two carousel types.
It would be great, *performance* wise, and developer *convenience* wise, to serve the flickity library only and use for both carousel types (without unofficially hacking it to achieve fade-transition).

**Other comments:**

- I haven't found a carousel that remotely beats flickity for all the reasons @cmalven listed. Plus the documentation is excellent. These things keep me coming back to flickity.
- Love @gavin310 's idea about the swipe gesture actively transitioning/controlling the opacity change. I don't think I've seen something like that out in the wild.

**Comment by jnicol** [comment] 2018-12-06 03:50
A +1 for this feature. Flickity is my preferred carousel, and fade transitions are the one feature I miss. About half the carousels I implement require fade transitions, and although the CSS hack described earlier in this thread does the trick, I would prefer for this to be officially supported by Flickity.

**Comment by kybradeck** [comment] 2018-12-14 06:00
I'm also using Flickity and I'm hoping to achieve somewhere between a swipe and a fade.

Imagine the fadeout solution as posted above, but the prev/next slides are offset by about 10% in either direction, so the direction of swipe is still visible—similar to current implementation, but more subtle than moving 100%.

**Comment by desandro** [comment] 2019-01-17 01:56
🚨🚨 I've decided to build and maintain fade behavior for Flickity. 🚨🚨

Work on `flickity-fade` is currently under way. I hope to release the new package in the next couple weeks. Only took 4 years 😅

Thanks to everyone for displaying interest in this feature and for your patience waiting for its realization.

**Comment by o-l-e** [comment] 2019-01-17 12:02
I understand wanting to keep Flickity as a pure swipe carousel, but i think this is a useful feature in some cases. I tend to use carousels as swipe for touch formats, and fade for mouse/keyboard based formats. It is more subtle and easier on the eyes on large screens with fade, with less movement.

I really like Flickity, and as a previous comment points out, it would be nice to not have to use two sliders. 

Keep up the good work @desandro!

**Comment by CHEWX** [comment] 2019-01-17 12:33
@o-l-e Look above your comment :)

**Comment by o-l-e** [comment] 2019-01-17 13:17
@CHEWX i know, i was just commenting since it was announced as a fetaure :)

**Comment by gavin310** [comment] 2019-01-17 16:47
@desandro This is awesome news! Thank you!

**Comment by intensr** [comment] 2019-01-18 16:18
finally nehehe

**Comment by desandro** [comment] 2019-01-30 16:59
You can now fade with Flickity v2.2.0. Add the [flickity-fade](https://github.com/metafizzy/flickity-fade) to enable `fade` option. See [Flickity `fade` docs](https://flickity.metafizzy.co/options.html#fade). `flickity-fade` is an add-on package, so [it needs to be installed separately](https://github.com/metafizzy/flickity-fade#install). Fade works with dragging, groupCells, wrapAround, imagesLoaded, and (hopefully) everything else in the Flickity feature-set.

I'm closing this issue as resolved. If you do run into a bug with `fade`, please open a new issue here or in the [flickity-fade Issue tracker](https://github.com/metafizzy/flickity-fade/issues)

lol Four years +1 day since OP. Thanks for hanging tight 🐻🌈

**Closed by desandro** 2019-01-30 16:59 UTC
Labels: feature request

**Comment by clarknelson** [comment] 2019-02-20 22:04
Thanks for this! using on my next project

**Comment by ptrwllrd** [comment] 2019-03-11 20:41
Legend!

**Comment by desandro** [comment] 2019-03-12 19:53
Thanks for all the positive support. I'm now locking this thread as its a big one so we can all move on.

If you do run into a bug with fade,  please open a new issue in the [flickity-fade Issue tracker](https://github.com/metafizzy/flickity-fade/issues) or on this main `flickity` tracker.
