### ISSUE TITLE
Left and Right buttons causes an error in IE8

### ISSUE THREAD

**Issue by aaronstezycki** [metafizzy/flickity#280] opened 2015-11-02 15:38 UTC
Left and Right bug in IE8 with version 1.1.1, not sure if this was the case with previous version 1.1.0. Just doesn't work, although it doesn't break Flickity, you can still drag left/right.

**Comment by desandro** [comment] 2015-11-03 03:09
Dupe of #281

**Closed by desandro** 2015-11-03 03:09 UTC
