### ISSUE TITLE
Scroll event on mobile

### ISSUE THREAD

**Issue by sutter** [metafizzy/flickity#12] opened 2015-01-27 11:34 UTC
Hello guys,
I have a little problem on mobile, when i scroll to the bottom, the view don't slide :(
Is it possible to listen only event horizontal ?
Thx

**Comment by desandro** [comment] 2015-01-27 14:15
This sounds like a duplicate of #3, which will be resolved in the next release.

**Closed by desandro** 2015-01-27 14:15 UTC
Labels: duplicate
