### ISSUE TITLE
flickity swipe is not working & page dot also click event in ios 15

### ISSUE THREAD

**Issue by vasanthangel4** [metafizzy/flickity#1184] opened 2021-10-20 19:51 UTC
Hello All, i have using flickity single vanilla js file, but it is not working the iOS 15 for swipe , but iOS 14, Android devices , Deskop working fine. we need to go live this due to this issue it is postponed. so i am totally stuck on it, i need your help. please help me on this.

**Comment by ermincelikovic** [comment] 2021-11-06 17:30
Any update here?

**Comment by shahriared** [comment] 2021-12-07 09:30
Same issue

**Comment by desandro** [comment] 2021-12-19 03:04
This is indeed an issue and I will have to investigate.

**Comment by desandro** [comment] 2021-12-19 03:08
Closing as a duplicate of #1177

**Closed by desandro** 2021-12-19 03:08 UTC
Labels: bug
