### ISSUE TITLE
Firefox display on hard refresh has incorrect height. (FF 43.0)

### ISSUE THREAD

**Issue by dennismarwood** [metafizzy/flickity#303] opened 2015-12-27 08:19 UTC
I forked your demo from http://codepen.io/desandro/pen/jEpxqJ and updated to 1.1.2. at http://codepen.io/dennismarwood/pen/obzQYM

I believe this is a similar issue to what I am seeing in my personal implementation of flickity. I could not trigger the issue in Chrome 47.0.

A refresh works as expected. However the initial landing and subsequent hard refreshes trigger the issue. Resizing the screen fixes the problem too.

**Comment by desandro** [comment] 2015-12-28 02:01
Thanks for reporting this issue. Sounds like a duplicate of #205

**Closed by desandro** 2015-12-28 02:01 UTC

**Comment by animaux** [comment] 2021-03-01 10:30
In case anyone stumbles upon this too. I had a similar problem with Firefox and the following settings:

``` js
imagesLoaded: true,
adaptiveHeight: true
```

None of the solutions mentioned in #205 did help. In the end the problem apparently was the `<img loading="lazy" … />`-attribute, that broke the correct height calculation for Firefox.
