### ISSUE TITLE
Error when using with Browserify

### ISSUE THREAD

**Issue by luxwan13** [metafizzy/flickity#727] opened 2018-03-29 03:48 UTC
You will get this error when you click/touch the carousel body: "bundle.min.js:1 Uncaught TypeError: this._dragPointerDown is not a function". I have debugged by myself. There is a call to this._dragPointerDown() in drag.js but this method does not get defined in any of the js files under node_modules/flickity/js.
You won't get this error if using a downloaded or CDN version as the proto._dragPointerDown = function is defined at line 2475 in dist/flickity.pkgd.js.
Please fix this problem so that we can use Browserify to require the library.

**Comment by raphaelokon** [comment] 2018-03-29 10:03
This is related to #724

**Comment by desandro** [comment] 2018-03-29 11:38
Thanks for reporting this issue. Closing as a duplicate of #724

**Closed by desandro** 2018-03-29 11:38 UTC
