### ISSUE TITLE
Strange flicker on iPad

### ISSUE THREAD

**Issue by landitus** [metafizzy/flickity#310] opened 2016-01-20 23:08 UTC
Trying Flickity on an iPad with iOS 9, I found a strange bug than makes the slider flicker on tap (disappears for a millisecond) and completely disappears when the user scrolls the page by dragging over the slider. It's very strange. I've tested it with the slider on the homepage and the same behaviour occurs. It works fine on the iPhone and on desktop browsers.

![img_0073](https://cloud.githubusercontent.com/assets/239215/12466217/99c082a2-bfb1-11e5-866e-0ac8b433b9f7.PNG)

**Comment by desandro** [comment] 2016-01-21 22:15
Thanks for reporting this issue. I'm not able to reproduce on my phone, but I'll keep this issue open for a while to see if others run into the same problem

**Comment by landitus** [comment] 2016-01-22 15:34
Ok, Just take into account it only happens on the iPad (not the Phone).

**Comment by desandro** [comment] 2016-05-10 12:04
Looks like no one else has responded so I'm going to close this issue.

**Closed by desandro** 2016-05-10 12:04 UTC
Labels: feedback welcome

**Comment by brattrson** [comment] 2017-01-13 07:38
Hi, same thing happeing in iphone safari iOS10.2
