### ISSUE TITLE
initialIndex and groupCells

### ISSUE THREAD

**Issue by runnickrun** [metafizzy/flickity#818] opened 2018-08-22 12:36 UTC
I'm trying to set initialIndex on a carousel where I use groupCells but apparently nothing happens. 
Any workaround to achieve the functionality?

**Test case:** https://codepen.io/runnick/pen/GXgbXr

**Comment by AdamJaggard** [comment] 2018-08-23 13:26
Because the cells are grouped initial index is now counting groups not cells, so there is no index 7 any more because there are only 4 groups. If you want the 7th cell then you can set initial index to 2 (to get the 3rd group). You could figure it our programatically if you know how many cells are in each group. No idea if this is intended behaviour or not.

**Comment by runnickrun** [comment] 2018-08-23 14:49
@AdamJaggard thanks, in my requirement though it should show as first slide (not just on the screen). 
So I was wondering maybe it's possible not to use groupCells but still retain the ability to move carousel by 3, 4, n slides per change.

**Comment by desandro** [comment] 2018-08-24 13:59
@runnickrun If you want to select a group slide by cell index or cell selector string, you can do so with [`selectCell` method](https://flickity.metafizzy.co/api.html#selectcell)

**Comment by runnickrun** [comment] 2018-08-24 17:04
@desandro Yeah, I tried that, but that still select group, so e.g. if item is 3rd in the group, it will be 3rd on the screen. What I'm trying to achieve is to show the selected item as first. 

Example of this could be seen here: 
https://www.dailymotion.com/video/x6s3cjm?playlist=x5z978

![image](https://user-images.githubusercontent.com/18515722/44597490-799e6b80-a7d8-11e8-90e4-892897f6df13.png)

upon clicking on the previous arrow, remaining slides are shown

![image](https://user-images.githubusercontent.com/18515722/44597531-a2266580-a7d8-11e8-8dff-42e3365a746c.png)

Hopefully that makes sense. I assume it means to kind of “split” the group and understand that it might not be possible by default, but would be great if you could provide some kind of direction.

**Comment by desandro** [comment] 2018-08-24 18:33
> it means to kind of “split” the group and understand that it might not be possible by default

Yeah, that is how `groupCells` is designed to work. If you need to align individual cells, then you cannot use groupCells. There is no API to workaround this behavior.

**Comment by desandro** [comment] 2019-01-29 21:59
In [v2.2.0](https://github.com/metafizzy/flickity/releases/tag/v2.2.0), you can now set [`initialIndex` to a selector string](https://flickity.metafizzy.co/options.html#initialindex). This will select the corresponding slide that contains the cell with the selector. I'm closing this issue as fixed. If you run into a problem with this feature, please open a new issue.

Thank you for your input 🌈🐻

**Closed by desandro** 2019-01-29 21:59 UTC
