### ISSUE TITLE
Animation pauses while the browser tab is in the background

### ISSUE THREAD

**Issue by drastick** [metafizzy/flickity#109] opened 2015-04-14 15:01 UTC
If you start Flickity, then change Chrome tabs to another page for 30 seconds and then switch back, you'll see something unexpected. Basically, all Flickity animation seems to stop while the tab isn't focused and then scrolls through multiple slides all at once until it catches up.

**Comment by nvartolomei** [comment] 2015-04-14 15:43
Are you using latest flickity build? See #6

**Comment by drastick** [comment] 2015-04-14 16:26
Yes I am using the most recent version.

**Comment by desandro** [comment] 2015-04-14 17:10
Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues). Also, what browser are you experiencing this in?

**Comment by evoactivity** [comment] 2015-04-20 12:29
I've seen this but I've not been able to reliably reproduce it. Latest Firefox Developer.

**Comment by drastick** [comment] 2015-04-22 14:47
Load this page and immediately switch to another tab.  Leave it open for a while (at least 5 minutes) then return to the tab. The issue seems to come from the page reloading while in the background.

http://s.codepen.io/drastick/debug/Pqopjj?

It sets a value in local storage so it doesn't continually reload the page so if you want to see the behavior again you will need to delete the 'reloaded' property in localstorage.

**Comment by desandro** [comment] 2015-04-27 20:55
I'm not able to reproduce this bug in a test case. I did see it occur once, but otherwise, I haven't seen the bug happen. I'll keep this issue open if others are able to reproduce it reliably.

**Comment by kukac7** [comment] 2015-06-16 14:10
:+1: 
it is important that it comes only after several minutes for the bug.
while other tabs to surf on. :laughing:

**Comment by desandro** [comment] 2015-11-04 13:23
Closing this issue as its been quiet for a while :tangerine:

**Closed by desandro** 2015-11-04 13:23 UTC

**Comment by slayer49** [comment] 2016-05-26 17:00
Possible to have a look at this again?  It still occurs, even in the codepen linked above.   To reproduce, simply open the codepen in Chrome, allow the slider to initialize, and start playing.   Open a new tab and brose around for a few minutes.  Return to the previous tab, and you will see the slider fast forward through all of the slides.

**Comment by IljaDaderko** [comment] 2016-06-22 13:17
+1

**Comment by gazdanebojsa** [comment] 2016-07-05 09:22
+1

**Comment by desandro** [comment] 2016-07-06 12:36
See #388
