### ISSUE TITLE
Pressing next / back buttons on iPad jumps 2 carousel-cells

### ISSUE THREAD

**Issue by PopcornDesign** [metafizzy/flickity#368] opened 2016-04-27 11:17 UTC
When pressing next / back buttons on iPad, it jumps 2 carousel-cells rather than 1.

This can be seen on your codepen. I have not modified it.

http://codepen.io/desandro/pen/azqbop

**Comment by ChristinMilloy** [comment] 2016-04-27 16:44
Confirmed this behaviour on multiple iPhones including iPhone 6 iOS 9.2.

We were able to replicate this bug on our own site as well as on the "demo" carousels in your own API docs here: http://flickity.metafizzy.co/api.html#methods

**Comment by desandro** [comment] 2016-04-27 20:00
Closing as a duplicate of #363. Follow that issue for further developments.

**Closed by desandro** 2016-04-27 20:00 UTC
