### ISSUE TITLE
"Contain: true" on wide monitor cause problem with prev next buttons

### ISSUE THREAD

**Issue by Akamajin** [metafizzy/flickity#619] opened 2017-08-21 16:18 UTC
Hi
When scrolling with prev or next button, upon reaching the end I can still click those buttons. after certain clicks it gets disabled. Increasing the page width emphasizes the effect. For example I have to click 4 times to start scrolling on 2560 pixel wide monitor.
When pageDots sets to true I can see what is really happening. But it doesn't make sense.

This is a fork from your examples. please don't tell me it is not reduced :)
https://codepen.io/Akumajin/pen/MvVNxM

**Comment by yaodingyd** [comment] 2017-08-21 19:05
@Akamajin  that's how it's intended. The official guide says it all:
> Contains cells to carousel element to prevent excess scroll at beginning or end.

Basically it means at beginning or end, if a cell is already in view and there are not enough cells to scroll to make it center-aligned, prevent the "excess" scroll, so there is no blank space for the first or last cell to be centered.

**Comment by desandro** [comment] 2017-08-22 14:01
Thanks for reporting this issue. See 289#issuecomment-157488885

Closing here as a duplicate.

**Comment by desandro** [comment] 2017-08-22 14:01
Duplicate of #289

**Closed by desandro** 2017-08-22 14:01 UTC
