### ISSUE TITLE
Flickity with lazy load

### ISSUE THREAD

**Issue by niros44** [metafizzy/flickity#307] opened 2016-01-17 17:00 UTC
Well i read all post here but did not find my answer...
When setting my image - can't i set it with a relative path (as it is set in my app)?
Please any help will be more than helpful.

Ps
I tried to set  my image
<img class="gallery-cell-image" src="/images/ddd.jpg"......
Or
Data-src.....
Or 
Data-flickity-lazyload....

None of them work with relative path

**Comment by desandro** [comment] 2016-01-17 18:02
Closing as a duplicate of #308

**Closed by desandro** 2016-01-17 18:02 UTC
