### ISSUE TITLE
after drag(throw), the selected cell is sometimes out of viewport

### ISSUE THREAD

**Issue by dennisbaum** [metafizzy/flickity#183] opened 2015-07-10 08:34 UTC
Using the freeScroll + wrapAround Props, it works quite nice selecting the next cell on drag.

But if i do a strong 'drag' and 'throw' the cells, the selected cell sometimes animates out of the viewport.
I think the check for the selected cell occurs on mouseUp, but it would be great, if the selection-check also occurs while the animation after the throw.

http://jsfiddle.net/vwpfyuzz/

**Comment by desandro** [comment] 2015-07-10 17:31
Thanks for reporting this issue. I believe this is a duplicate of #181

**Closed by desandro** 2015-07-10 17:31 UTC

**Comment by dennisbaum** [comment] 2015-07-10 18:14
I have read that issue too, but i wasn't sure. But you will know that better.
Do you manage the selection also while animate the slider after a throw? I can't find that...

**Comment by desandro** [comment] 2015-07-10 18:22
It happens in [`dragEnd` and `dragEndRestingSelect`](https://github.com/metafizzy/flickity/blob/v1.1.0/js/drag.js#L229)
