### ISSUE TITLE
Dragging issue when loaded via Webpack

### ISSUE THREAD

**Issue by MattPurland** [metafizzy/flickity#728] opened 2018-03-29 12:16 UTC
Hi,

Flickity is generally working fine, but as soon as I attempt to drag to the next/previous slide I get the following the in the console:

Uncaught TypeError: this._dragPointerDown is not a function
    at Flickity.proto._pointerDownDefault (drag.js:175)
    at Flickity.proto.pointerDown (drag.js:171)
    at Flickity.proto._pointerDown (unipointer.js:128)
    at Flickity.proto.onpointerdown (unipointer.js:107)
    at Flickity.proto.handleEvent (unipointer.js:77)

Which in turn stops the carousel from working all together. Any ideas?

**Comment by desandro** [comment] 2018-03-29 17:02
Duplicate of #724. Fix coming.

**Closed by desandro** 2018-03-29 17:02 UTC
