### ISSUE TITLE
staticClick fires when dragging on iPhone

### ISSUE THREAD

**Issue by cmeeren** [metafizzy/flickity#221] opened 2015-08-20 11:28 UTC
I'm using the following code:

````javascript
$carousel = $('.flickity-carousel').flickity({
  ...
});

$carousel.on('staticClick', function() {
  $('#modal-read-buttons').modal('show');
});
````

Works fine on PC and Android, but on iPhone the modal shows even when sliding.

**Comment by desandro** [comment] 2015-08-20 20:10
I wasn't able to reproduce this issue on my iPhone. See demo http://s.codepen.io/desandro/debug/RNQgxe . Can you provide a reduced test case?

**Comment by cmeeren** [comment] 2015-08-21 13:24
Unfortunately no. One of my test users reported this (on a rather complex website), I don't have an iPhone myself. I worked around it by placing the desired javascript code in a function called in an ``href`` attribute instead. Unfortunately I don't have the time to hunt this down.

**Comment by desandro** [comment] 2015-08-31 19:22
Closing as a duplicate of #123

**Closed** 2015-08-31 19:49 UTC
Labels: duplicate, test case required
