### ISSUE TITLE
Text blurring

### ISSUE THREAD

**Issue by howells** [metafizzy/flickity#254] opened 2015-09-30 10:30 UTC
I have a problem whereby the text contained within a flickity cell seems to be very blurry - is there anything I can do to handle this?

![screen shot 2015-09-30 at 11 28 01](https://cloud.githubusercontent.com/assets/145849/10190716/842c7fca-6766-11e5-8e87-154c31cd7c32.png)

Comparison to regular text:

![screen shot 2015-09-30 at 11 31 11](https://cloud.githubusercontent.com/assets/145849/10190752/c6198f22-6766-11e5-9f61-a2ed04ca20c0.png)

**Comment by desandro** [comment] 2015-09-30 15:17
Hi Daniel, Thanks for reporting this issue. This may be caused by Flickity's use of `transform` for positioning. What browser are you experiencing this in? Any change you have a live URL I can take a look at?

**Comment by howells** [comment] 2015-09-30 15:18
It's in Chrome, and yeah you can see it right here: http://katamama-staging.future-corp.net/ scroll down to "Collaborations + Features" - thanks!!

**Comment by desandro** [comment] 2016-02-07 18:08
I wasn't able to reproduce the issue. Looks like no one else has chimed in as well. Closing this issue for now :ghost:

**Closed by desandro** 2016-02-07 18:08 UTC
Labels: under investigation

**Comment by marjanbajc** [comment] 2016-07-22 17:26
We are having the same issue.

translate3d( 0, 0, 0), perspective(1px), scale(1.1) didn't work.

**Comment by dangelion** [comment] 2017-04-28 09:12
Also here I get blurry text inside the cells. I'm on Mac Chrome 58.0.3029.81 (64-bit)

translate3d(0, 0, 0), perspective(1px), scale(1.1) didn't work for me

**Comment by howells** [comment] 2017-04-28 09:14
I had the problem again but seemed to be fixed by not using percentage positioning - give that s try

**Comment by dangelion** [comment] 2017-04-28 09:33
If you mean defining cells width with px instead of %, it works only sometimes

**Comment by howells** [comment] 2017-04-28 11:30
@dangelion http://flickity.metafizzy.co/options.html#percentposition

**Comment by dangelion** [comment] 2017-04-28 14:12
It seems work, but I need to investigate more. Thanks for the advice
